In [170]:
import numpy as np                                               #this model is used for the linear matrix
import pandas as pd                                              #used for data processing and for read the file(csv)
import os                                                        #used for upload the file

In [140]:
movie_title = pd.read_csv('tmdb_5000_movies.csv')                   #reading the movies file
credit_movies = pd.read_csv('tmdb_5000_credits.csv')                #credit in the movies files

In [141]:
movie_title.head(10)                                                 # checking the file which is uploaded

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  258000000  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   
6  260000000  [{"id": 16, "name": "Animation"}, {"id": 10751...   
7  280000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
8  250000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
9  250000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            homepage      id  \
0                        http://www.avatarmovie.com/   19995   
1       http://disney.go.com/disneypictures/pirates/     285   
2        http://www.sonypictures.com/movies/spectre/  206647   
3                 http://www.thedarkknightrises.com/   49026   
4               http://movies.disney.com/john-carter   49529   
5    http://www.sonypictures.com/movies/spider-man3/     559   
6       http://disney.go.com/disneypictures/tangled/   38757   
7  http://marvel.com/movies/movie/193/avengers_ag...   99861   
8  http://harrypotter.warnerbros.com/harrypottera...     767   
9       http://www.batmanvsupermandawnofjustice.com/  209112   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   
5  [{"id": 851, "name": "dual identity"}, {"id": ...                en   
6  [{"id": 1562, "name": "hostage"}, {"id": 2343,...                en   
7  [{"id": 8828, "name": "marvel comic"}, {"id": ...                en   
8  [{"id": 616, "name": "witch"}, {"id": 2343, "n...                en   
9  [{"id": 849, "name": "dc comics"}, {"id": 7002...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   
5                              Spider-Man 3   
6                                   Tangled   
7                   Avengers: Age of Ultron   
8    Harry Potter and the Half-Blood Prince   
9        Batman v Superman: Dawn of Justice   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   
5  The seemingly invincible Spider-Man goes up ag...  115.699814   
6  When the kingdom's most wanted-and most charmi...   48.681969   
7  When Tony Stark tries to jumpstart a dormant p...  134.279229   
8  As Harry begins his sixth year at Hogwarts, he...   98.885637   
9  Fearing the actions of a god-like Super Hero l...  155.790452   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   
5  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
6  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
7  [{"name": "Marvel Studios", "i

In [142]:
movie_title.shape                                               #checking the shape of the file.

(4803, 20)

In [143]:
credit_movies.head(10)                                         # checking the file which is uploaded

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   
5       559                              Spider-Man 3   
6     38757                                   Tangled   
7     99861                   Avengers: Age of Ultron   
8       767    Harry Potter and the Half-Blood Prince   
9    209112        Batman v Superman: Dawn of Justice   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   
5  [{"cast_id": 30, "character": "Peter Parker / ...   
6  [{"cast_id": 34, "character": "Flynn Rider (vo...   
7  [{"cast_id": 76, "character": "Tony Stark / Ir...   
8  [{"cast_id": 3, "character": "Harry Potter", "...   
9  [{"cast_id": 18, "character": "Bruce Wayne / B...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...  
5  [{"credit_id": "52fe4252c3a36847f80151a5", "de...  
6  [{"credit_id": "52fe46db9251416c91062101", "de...  
7  [{"credit_id": "55d5f7d4c3a3683e7e0016eb", "de...  
8  [{"credit_id": "52fe4273c3a36847f801fab1", "de...  
9  [{"credit_id": "553bf23692514135c8002886", "de...

In [144]:
movies_pro = movie_title.merge(credit_movies,on='title')  # merging the both csv file into 1 using the column name is title
                                                          #(which is similar in both of files)

In [145]:
movies_pro.head(10)   # checking up new the file which is created

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  258000000  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   
6  260000000  [{"id": 16, "name": "Animation"}, {"id": 10751...   
7  280000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
8  250000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
9  250000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            homepage      id  \
0                        http://www.avatarmovie.com/   19995   
1       http://disney.go.com/disneypictures/pirates/     285   
2        http://www.sonypictures.com/movies/spectre/  206647   
3                 http://www.thedarkknightrises.com/   49026   
4               http://movies.disney.com/john-carter   49529   
5    http://www.sonypictures.com/movies/spider-man3/     559   
6       http://disney.go.com/disneypictures/tangled/   38757   
7  http://marvel.com/movies/movie/193/avengers_ag...   99861   
8  http://harrypotter.warnerbros.com/harrypottera...     767   
9       http://www.batmanvsupermandawnofjustice.com/  209112   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   
5  [{"id": 851, "name": "dual identity"}, {"id": ...                en   
6  [{"id": 1562, "name": "hostage"}, {"id": 2343,...                en   
7  [{"id": 8828, "name": "marvel comic"}, {"id": ...                en   
8  [{"id": 616, "name": "witch"}, {"id": 2343, "n...                en   
9  [{"id": 849, "name": "dc comics"}, {"id": 7002...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   
5                              Spider-Man 3   
6                                   Tangled   
7                   Avengers: Age of Ultron   
8    Harry Potter and the Half-Blood Prince   
9        Batman v Superman: Dawn of Justice   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   
5  The seemingly invincible Spider-Man goes up ag...  115.699814   
6  When the kingdom's most wanted-and most charmi...   48.681969   
7  When Tony Stark tries to jumpstart a dormant p...  134.279229   
8  As Harry begins his sixth year at Hogwarts, he...   98.885637   
9  Fearing the actions of a god-like Super Hero l...  155.790452   

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0   
5  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   139.0  

In [146]:
movies_pro = movies_pro[['movie_id','title','overview','genres','keywords','cast','crew']] #taking or creating the file with 
                      #the require data through which the recommend for movies.

In [147]:
movies_pro.head(10)                                               # checking up only the data we selected

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   
5       559                              Spider-Man 3   
6     38757                                   Tangled   
7     99861                   Avengers: Age of Ultron   
8       767    Harry Potter and the Half-Blood Prince   
9    209112        Batman v Superman: Dawn of Justice   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   
5  The seemingly invincible Spider-Man goes up ag...   
6  When the kingdom's most wanted-and most charmi...   
7  When Tony Stark tries to jumpstart a dormant p...   
8  As Harry begins his sixth year at Hogwarts, he...   
9  Fearing the actions of a god-like Super Hero l...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   
6  [{"id": 16, "name": "Animation"}, {"id": 10751...   
7  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
8  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
9  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   
5  [{"id": 851, "name": "dual identity"}, {"id": ...   
6  [{"id": 1562, "name": "hostage"}, {"id": 2343,...   
7  [{"id": 8828, "name": "marvel comic"}, {"id": ...   
8  [{"id": 616, "name": "witch"}, {"id": 2343, "n...   
9  [{"id": 849, "name": "dc comics"}, {"id": 7002...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   
5  [{"cast_id": 30, "character": "Peter Parker / ...   
6  [{"cast_id": 34, "character": "Flynn Rider (vo...   
7  [{"cast_id": 76, "character": "Tony Stark / Ir...   
8  [{"cast_id": 3, "character": "Harry Potter", "...   
9  [{"cast_id": 18, "character": "Bruce Wayne / B...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...  
5  [{"credit_id": "52fe4252c3a36847f80151a5", "de...  
6  [{"credit_id": "52fe46db9251416c91062101", "de...  
7  [{"credit_id": "55d5f7d4c3a3683e7e0016eb", "de...  
8  [{"credit_id": "52fe4273c3a36847f801fab1", "de...  
9  [{"credit_id": "553bf23692514135c8002886", "de...

In [148]:
import ast  #used to Analyze the text

In [149]:
def convert(text):                     #creating a function to remove the names from the genres
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L 

In [150]:
movies_pro.dropna(inplace=True)

In [151]:
movies_pro['genres'] = movies_pro['genres'].apply(convert)       #applying the function to the genres and keywords
movies_pro['keywords'] = movies_pro['keywords'].apply(convert)
movies_pro.head(10)                                              #checking up the file

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   
5       559                              Spider-Man 3   
6     38757                                   Tangled   
7     99861                   Avengers: Age of Ultron   
8       767    Harry Potter and the Half-Blood Prince   
9    209112        Batman v Superman: Dawn of Justice   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   
5  The seemingly invincible Spider-Man goes up ag...   
6  When the kingdom's most wanted-and most charmi...   
7  When Tony Stark tries to jumpstart a dormant p...   
8  As Harry begins his sixth year at Hogwarts, he...   
9  Fearing the actions of a god-like Super Hero l...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   
5                   [Fantasy, Action, Adventure]   
6                            [Animation, Family]   
7           [Action, Adventure, Science Fiction]   
8                   [Adventure, Fantasy, Family]   
9                   [Action, Adventure, Fantasy]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   
5  [dual identity, amnesia, sandstorm, love of on...   
6  [hostage, magic, horse, fairy tale, musical, p...   
7  [marvel comic, sequel, superhero, based on com...   
8  [witch, magic, broom, school of witchcraft, wi...   
9  [dc comics, vigilante, superhero, based on com...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   
5  [{"cast_id": 30, "character": "Peter Parker / ...   
6  [{"cast_id": 34, "character": "Flynn Rider (vo...   
7  [{"cast_id": 76, "character": "Tony Stark / Ir...   
8  [{"cast_id": 3, "character": "Harry Potter", "...   
9  [{"cast_id": 18, "character": "Bruce Wayne / B...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...  
5  [{"credit_id": "52fe4252c3a36847f80151a5", "de...  
6  [{"credit_id": "52fe46db9251416c91062101", "de...  
7  [{"credit_id": "55d5f7d4c3a3683e7e0016eb", "de...  
8  [{"credit_id": "52fe4273c3a36847f801fab1", "de...  
9  [{"credit_id": "553bf23692514135c8002886", "de...

In [153]:
def convert3(text):                          #creating a function to remove id , name and space in cast column
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L 

In [154]:
movies_pro['cast'] = movies_pro['cast'].apply(convert)                  #appling the function to cast and coverting it into lambda form
movies_pro['cast'] = movies_pro['cast'].apply(lambda x:x[0:3])
movies_pro.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                               cast  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3      [Christian Bale, Michael Caine, Gary Oldman]   
4    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [155]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L 

In [156]:
movies_pro['crew'] = movies_pro['crew'].apply(fetch_director)
movies_pro.sample(5)

movie_id                     title  \
2006     21349         Anywhere But Here   
476      19959                Surrogates   
1131     25189  The Mirror Has Two Faces   
3123     22805                Motherhood   
4004     11072           Blazing Saddles   

                                               overview  \
2006  In this adaptation of the Mona Simpson novel, ...   
476   Set in a futuristic world where humans live in...   
1131  Rose Morgan (Barbara Streisand), who still liv...   
3123  Motherhood is a comedy written and directed by...   
4004  A town – where everyone seems to be named John...   

                                   genres  \
2006             [Drama, Comedy, Romance]   
476   [Action, Science Fiction, Thriller]   
1131             [Comedy, Drama, Romance]   
3123                      [Comedy, Drama]   
4004                    [Western, Comedy]   

                                               keywords  \
2006                                            [dream]   
476                                   [clone, dystopia]   
1131  [sex, professor, wedding, woman director, colu...   
3123                [mother role, blog, woman director]   
4004  [gun, saloon, governor, marching band, comedy,...   

                                                 cast                   crew  
2006  [Susan Sarandon, Natalie Portman, Hart Bochner]           [Wayne Wang]  
476     [Bruce Willis, Radha Mitchell, Rosamund Pike]      [Jonathan Mostow]  
1131  [Barbra Streisand, Jeff Bridges, Lauren Bacall]     [Barbra Streisand]  
3123    [Uma Thurman, Minnie Driver, Anthony Edwards]  [Katherine Dieckmann]  
4004     [Cleavon Little, Gene Wilder, Harvey Korman]           [Mel Brooks]

In [157]:
def collapse(L):                                     #creating a function to remove space in column
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [158]:
movies_pro['cast'] = movies_pro['cast'].apply(collapse)                  #applying the function and checking it
movies_pro['crew'] = movies_pro['crew'].apply(collapse)
movies_pro['genres'] = movies_pro['genres'].apply(collapse)
movies_pro['keywords'] = movies_pro['keywords'].apply(collapse)
movies_pro.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   
3              [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, ScienceFiction]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                                            cast                crew  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]      [JamesCameron]  
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]     [GoreVerbinski]  
2      [DanielCraig, ChristophWaltz, LéaSeydoux]         [SamMendes]  
3      [ChristianBale, MichaelCaine, GaryOldman]  [ChristopherNolan]  
4    [TaylorKitsch, LynnCollins, SamanthaMorton]     [AndrewStanton]

In [159]:
movies_pro['overview'] = movies_pro['overview'].apply(lambda x:x.split())
movies_pro['comb'] = movies_pro['overview'] + movies_pro['genres'] + movies_pro['keywords'] + movies_pro['cast'] + movies_pro['crew']
final = movies_pro.drop(columns=['overview','genres','keywords','cast','crew'])
final.head(10)

#applying the lambda to overview
#merging all the columns into one column named as comb

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   
5       559                              Spider-Man 3   
6     38757                                   Tangled   
7     99861                   Avengers: Age of Ultron   
8       767    Harry Potter and the Half-Blood Prince   
9    209112        Batman v Superman: Dawn of Justice   

                                                comb  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...  
2  [A, cryptic, message, from, Bond’s, past, send...  
3  [Following, the, death, of, District, Attorney...  
4  [John, Carter, is, a, war-weary,, former, mili...  
5  [The, seemingly, invincible, Spider-Man, goes,...  
6  [When, the, kingdom's, most, wanted-and, most,...  
7  [When, Tony, Stark, tries, to, jumpstart, a, d...  
8  [As, Harry, begins, his, sixth, year, at, Hogw...  
9  [Fearing, the, actions, of, a, god-like, Super...

In [160]:
final['comb'] = final['comb'].apply(lambda x: " ".join(x))           #covering the comb column into lambda function
final.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                comb  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [161]:
final.to_csv('final_movies.csv',index=False)               #saving the csv into folder

In [171]:
from sklearn.feature_extraction.text import CountVectorizer             #import a ml model countvectorizer and giving max words
counter = CountVectorizer(max_features=10000,stop_words='english')  
print(counter)

CountVectorizer(max_features=10000, stop_words='english')


In [172]:
vectorizer = counter.fit_transform(final['comb']).toarray()   #applying the model and toarray
print(vectorizer)                                             #checking up the shape 
vectorizer.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(4806, 10000)

In [181]:
from sklearn.metrics.pairwise import cosine_similarity         #applying the martix and cosine similarity  

similar = cosine_similarity(vectorizer)
similar

array([[1.        , 0.07644708, 0.05096472, ..., 0.02111002, 0.02272727,
        0.        ],
       [0.07644708, 1.        , 0.05714286, ..., 0.02366905, 0.        ,
        0.        ],
       [0.05096472, 0.05714286, 1.        , ..., 0.02366905, 0.        ,
        0.        ],
       ...,
       [0.02111002, 0.02366905, 0.02366905, ..., 1.        , 0.06333005,
        0.04174829],
       [0.02272727, 0.        , 0.        , ..., 0.06333005, 1.        ,
        0.04494666],
       [0.        , 0.        , 0.        , ..., 0.04174829, 0.04494666,
        1.        ]])

In [180]:
similar.shape                                                      #checking up the shape

(4806, 4806)

In [179]:
similar.size                                                  #checking up the size

23097636

In [175]:
final[final['title'] == 'The Lego Movie'].index[0]          #see the recommend for the word or seeing the movie location.

744

In [167]:
def recommend(movie):                                            #making function for the recommend for the movies
    movies = final[final['title'] == movie].index[0]
    distance = sorted(list(enumerate(similar[movies])),reverse=True,key = lambda x: x[1])
    for i in distance[1:6]:
        print(final.iloc[i[0]].title)

recommend('Gandhi')                                           #results

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan


In [168]:
import pickle                                                #saving the model for website.
pickle.dump(final,open('list_movies.pkl','wb'))
pickle.dump(similar,open('similar.pkl','wb'))